### ISSUE TITLE
Front-End to Server JSON interaction

### ISSUE THREAD

**Issue by gaycodegal** [hydrodog/LiquiZ2#3]
The front end is ready to send quizzes to the server through JSON. I wrote a README to describe what the front end will send to the server. When you have a relative or absolute path you would like the quiz to send an ajax request to, email me and I'll set up Editor.html with your path so that you can launch it and test with that address. Here is the readme describing the JSON: https://github.com/hydrodog/LiquiZ2/blob/master/LiquiZ2/WebContent/js/README_JSON_DOCUMENTATION.txt

**Comment by hydrodog** [comment]
Thanks Stephen I dropped the ball but this is the best way
